version: 2
jobs:
  build:
    docker: &docker_image
      - image: circleci/node:7.10

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Test
          command: |
            npm install
            npm run test:coverage

      - run:
          name: Codecov
          command: CODECOV_TOKEN=${CODECOV_TOKEN} npm run codecov
          when: always

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  no-release:
    docker: *docker_image
    steps:
      - run: exit 0

  patch-release:
    docker: *docker_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Run patch release
          command: |
            npm install
            npm run release:patch
      - save_cache:
          key: npm-deps-v1{{ checksum "package.json" }}
          paths:
            - node_modules

  minor-release:
    docker: *docker_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Run minor release
          command: |
            npm install
            npm run release:minor
      - save_cache:
          key: npm-deps-v1{{ checksum "package.json" }}
          paths:
            - node_modules

  major-release:
    docker: *docker_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Run major release
          command: |
            npm install
            npm run release:major
      - save_cache:
          key: npm-deps-v1{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - no-release:
          type: approval
          requires:
            - build
      - patch-release:
          type: approval
          requires:
            - build
      - minor-release:
          type: approval
          requires:
            - build
      - major-release:
          type: approval
          requires:
            - build

