# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/project/react-code-input
  docker:
    - image: circleci/node:8-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - v1-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
      #      - v1-vue-{{ .Branch }}-
      #      - v1-vue-
      - run: npm install
      - save_cache:
          key: v1-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-router

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:coverage

  test-codecov:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      # add codecov
      - run: CODECOV_TOKEN=444a47a4-b0fb-4cf1-8105-19a403cb7bbd npm run codecov

workflows:
  version: 2
  build-and-parallel-test:
    jobs:
      - build
      - test-unit:
          requires:
            - build
      - test-codecov:
          requires:
            - build